version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: market-pos-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: market_user
      POSTGRES_PASSWORD: market_pass
      POSTGRES_DB: market_pos_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
